name: Build and Release Kotlin/Native Binary

on:
  release:
    types: [ created ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Replace version in VersionCommand.kt
        run: |
          perl -pi -e 's/__VERSION__/${{ github.event.release.tag_name }}/g' capjoy/src/nativeMain/kotlin/capjoy/command/VersionCommand.kt

      - name: Build Kotlin/Native binary
        run: ./gradlew build

      - name: Archive the build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: binary
          path: capjoy/build/bin/native/releaseExecutable/*

  release:
    needs: build
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: binary
          path: ./build

      - name: Show status of downloaded artifacts
        run: ls -lR ./build

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: ./build/capjoy.kexe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
